ignore:
- "**/*_test.go"
- "**/mocks/*.go"
- "test/**/*"
- "vendor/**/*"
coverage:
  status:
    # we've found this not to be useful
    patch: off
    project:
      default:
        # allow test coverage to drop by 2%, assume that it's typically due to CI problems
        threshold: 2
