include:
  - project: KeliTeamCorti/tribes/reliability-and-devx/cicd/jsk_gitlab_jobs
    file: pipelines/global.yml
    ref: 5.12.8 # Pipelines are versionned, to avoid breaking changes

variables:
  # Make sure you change <module> placeholder.
  MODULE: software_factory
  JCI_ECR_REPOSITORY: $MODULE/argocd_image_updater
  JCI_DISABLE_SONARCLOUD: "true"
  JCI_BUILD_PATH: "/"
  JCI_BUILD_CI_IMAGE_DOCKERFILE_PATH: "Dockerfile"
  JCI_BUILD_RUN_IMAGE_DOCKERFILE_PATH: "Dockerfile"
  JCI_AWS_ECR_CREATE_REPOSITORY_ENABLED: "true"
  JCI_RELEASER_CONFIG: |
    [semantic_release]
    major_on_zero = false
    tag_format = "{version}"
    version_variables = [ ${JCI_RELEASER_VERSION_VARIABLES} ]
    version_toml = [ ${JCI_RELEASER_VERSION_TOML} ]
    commit_message = "chore(release): bump version {version}"
    
    [semantic_release.branches."$CI_COMMIT_BRANCH"]
    match = "($CI_COMMIT_BRANCH)"
    prerelease_token = "rc"
    prerelease = false
    
    [semantic_release.commit_parser_options]
    minor_tags = [ "feat" ]
    patch_tags = [ "build", "chore", "ci", "docs", "fix", "perf", "style", "refactor", "test", "bump" ]
    
    [semantic_release.remote]
    type = "gitlab"
    
    [semantic_release.publish]
    upload_to_vcs_release = false

