include:
  - project: 'platform/templates/gitlab-ci-cd-templates'
    ref: 'v5'
    file: 'docker-build-push.yml'

build-image:
  extends: .image-build-push
  variables:
    DOCKERFILE_PATH: 'Dockerfile'
  after_script:
    - docker tag ${DESTINATION}:${IMAGE_TAG_SUFFIX} harbor.stage.private.oxyplatform.io/platform-internal/argocd-image-updater:${IMAGE_TAG_SUFFIX}
    - docker push harbor-ext.stage.private.oxyplatform.io/platform-internal/argocd-image-updater:${IMAGE_TAG_SUFFIX}