run:
  timeout: 2m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs:
    - vendor/
linters:
  enable:
    - vet
    - goimports
    - ineffassign
    - unconvert
    - unparam
    - unused
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj-labs/argocd-image-updater
service:
  golangci-lint-version: 1.52.2
