version: "2"
linters:
  enable:
    - misspell
    - unconvert
    - ineffassign
    - unused
    - govet
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go
      - vendor/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/argoproj-labs/argocd-image-updater
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - vendor/
      - third_party$
      - builtin$
      - examples$
run: 
  timeout: 5m
