# permissions for end users to edit imageupdaters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-updater
    app.kubernetes.io/managed-by: kustomize
  name: imageupdater-editor-role
rules:
- apiGroups:
  - argocd-image-updater.argoproj.io
  resources:
  - imageupdaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd-image-updater.argoproj.io
  resources:
  - imageupdaters/status
  verbs:
  - get
