apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/managed-by: kustomize
  name: argocd-image-updater-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater-leader-election-role
subjects:
- kind: ServiceAccount
  name: argocd-image-updater-controller
  namespace: argocd-image-updater-system
