---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argocd-image-updater.argoproj.io
  resources:
  - imageupdaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd-image-updater.argoproj.io
  resources:
  - imageupdaters/finalizers
  verbs:
  - update
- apiGroups:
  - argocd-image-updater.argoproj.io
  resources:
  - imageupdaters/status
  verbs:
  - get
  - patch
  - update
