apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/managed-by: kustomize
  name: argocd-image-updater-controller
  namespace: argocd-image-updater-system
