apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  labels:
    app.kubernetes.io/name: image-updater
    app.kubernetes.io/managed-by: kustomize
  name: imageupdater-sample-short
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "image-updater-001"
      images:
        - alias: "nginx"
          imageName: "nginx:1.17.10"
