# More info on this config: https://dependabot-gitlab.gitlab.io/dependabot/config/configuration.html
---
version: 2
updates:
  - package-ecosystem: 
    directory: /
    schedule:
      interval: daily
    pull-request-branch-name:
      prefix: "feature-dependabot"
    open-pull-requests-limit: 10
