// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	schema1 "github.com/docker/distribution/manifest/schema1"
)

// RegistryClient is an autogenerated mock type for the RegistryClient type
type RegistryClient struct {
	mock.Mock
}

// ManifestV1 provides a mock function with given fields: repository, reference
func (_m *RegistryClient) ManifestV1(repository string, reference string) (*schema1.SignedManifest, error) {
	ret := _m.Called(repository, reference)

	var r0 *schema1.SignedManifest
	if rf, ok := ret.Get(0).(func(string, string) *schema1.SignedManifest); ok {
		r0 = rf(repository, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema1.SignedManifest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repository, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Tags provides a mock function with given fields: nameInRepository
func (_m *RegistryClient) Tags(nameInRepository string) ([]string, error) {
	ret := _m.Called(nameInRepository)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(nameInRepository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nameInRepository)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
