apiVersion: v1
kind: Service
metadata:
  name: argocd-image-updater-service
spec:
  selector:
    app.kubernetes.io/name: argocd-image-updater
  type: NodePort
  ports:
  - name: server-port
    protocol: TCP
    port: 8080
    targetPort: 8080
