apiVersion: v1
kind: Service
metadata:
  name: argocd-image-updater-service
spec:
  selector:
    control-plane: argocd-image-updater-controller
  type: NodePort
  ports:
  - name: server-port
    protocol: TCP
    port: 8080
    targetPort: 8082
