name: Spell checking
on:
  push:
    branches:
    - master
    - 'release-*'
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - uses: check-spelling/check-spelling@v0.0.22
