name: Spell checking
on:
  push:
    branches:
    - master
    - 'release-*'
  pull_requests:
    branches:
    - master

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 5
    - uses: check-spelling/check-spelling@prerelease
